name: Build & Upload Python Package to PyPI

on:
  release:
    types: [ published ]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v5

      - name: Install uv 💜
        uses: astral-sh/setup-uv@v6

      - name: Install and run ruff 🐶
        uses: astral-sh/ruff-action@v3

      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies 📦
        run: |
          uv sync --all-groups --frozen

      - name: Lint with flake8 ❄️
        run: |
          uv run flake8 --config flake8.cfg

      - name: Test with pytest ✅
        run: |
          uv run pytest tests

      - name: Build and publish 🚀
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv build
          uv publish
